Add abort-on-container-exit option to compose.up
gabrieldemarmiesse/python-on-whales pull request #168
Opened 2021-05-20 21:49 UTC by anesabml

2021-05-21 13:08 UTC, anesabml commented
@gabrieldemarmiesse any idea why the flake8 command fails?

2021-05-21 19:57 UTC, gabrieldemarmiesse commented
Going at the bottom of the logs, a bit hidden, I see
```
./python_on_whales/components/compose/cli_wrapper.py:267:72: W291 trailing whitespace
#13 2.285 ./python_on_whales/components/compose/cli_wrapper.py:270:25: W291 trailing whitespace
```
I believe this is the reason

2021-05-21 22:22 UTC, anesabml commented
I fixed those lint issues but the ci still fails on my local machine.

2021-05-22 14:42 UTC, gabrieldemarmiesse commented
We use the balck formatter on this codebase, this is why the ci is complaining.

Could you do `isort ./ && black ./` and push again? This should fix those formatting problems. Thanks!

2021-05-24 22:20 UTC, anesabml commented
@gabrieldemarmiesse  I run the test I added on my local machine (MacBook Pro), any ideas why it fails in CI?

2021-05-25 07:42 UTC, gabrieldemarmiesse commented
I will take a look today, thanks again for the pull request!

2021-05-25 08:29 UTC, gabrieldemarmiesse commented
I see the problem, but I don't know the root cause.
In the CI, during the test, we see:
```
alpine_1  | 5 packets transmitted, 0 packets received, 100% packet loss
```

locally, I have 
```
alpine_1  | 5 packets transmitted, 5 packets received, 0% packet loss
```

I wonder if we're just unlucky and that's a temporary network issue in the CI, I'll restart the job.

2021-05-25 08:56 UTC, gabrieldemarmiesse commented
It's not luck it seems. I'll try to find out how we can fix this test.

2021-05-25 09:23 UTC, gabrieldemarmiesse requested changes
Thank you for the pull request, just a few changes to make the docs better

2021-05-25 09:23 UTC, gabrieldemarmiesse commented on python_on_whales/components/compose/cli_wrapper.py
> +                Incompatible with --abort-on-container-exit.
```suggestion
                Incompatible with `abort_on_container_exit=True`.
```

2021-05-25 09:23 UTC, gabrieldemarmiesse commented on python_on_whales/components/compose/cli_wrapper.py
> +                stopped. Incompatible with --detach.
```suggestion
                stopped. Incompatible with `detach=True`.
```

2021-05-25 19:57 UTC, anesabml commented
Thanks a lot for helping with debugging the issue, I will make the required changes regarding the docs.

2021-05-25 19:59 UTC, anesabml commented on python_on_whales/components/compose/cli_wrapper.py
> +                Incompatible with --abort-on-container-exit.
That's better thanks for the suggestion

2021-05-25 19:59 UTC, anesabml commented on python_on_whales/components/compose/cli_wrapper.py
> +                stopped. Incompatible with --detach.
That's better thanks for the suggestion

2021-05-25 21:04 UTC, gabrieldemarmiesse approved these changes

2021-05-26 12:05 UTC, gabrieldemarmiesse commented
It seems there is an issue on master, the CI doesn't pass suddently. Very likely something was updated and it caused the various issues we saw in your pull request. You can consider that this pull request is done (it was approuved). I'll work on the CI to make it work again. Thanks for your patience :)

2021-05-27 14:55 UTC, merged

2021-05-27 18:55 UTC, anesabml commented
Thank you for your help.