Allow container selection in 'docker stats'
gabrieldemarmiesse/python-on-whales pull request #447
Opened 2023-06-01 22:21 UTC by MisterOwlPT

Hi! 😃 

I am using _python_on_whales_ at work to retrieve resources consumption per container (using command `docker stats`).

Currently, _python_on_whales_ seems to _always_ retrieve information about "all" containers:

```python
>>> from python_on_whales import docker
>>> docker.stats()
[<<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=9b136659b81a, container_id=9b136659b81af7dec9ffbacc58b6e48cf8376cee89e7fabcb0924835237a3c4f, memory_percentage=0.0, memory_used=397312, memory_limit=8324720361, container_name=amazing_fermat, net_upload=5070, net_download=0>,
 <<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=94f96d8b61d8, container_id=94f96d8b61d8f4c0b60b62b158c48d124407ef13fbbce6b0ab40ec92abf84861, memory_percentage=0.0, memory_used=413696, memory_limit=8324720361, container_name=sweet_jennings, net_upload=5110, net_download=0>,
 <<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=118be246cc17, container_id=118be246cc172ed7b18d43372d1b322d3d1c77c9e44b8d24b155aec0d09f7fd9, memory_percentage=0.0, memory_used=405504, memory_limit=8324720361, container_name=nifty_buck, net_upload=5370, net_download=0>]
```

The "problem" here is that I only require information concerning a _subset_ of the listed containers.
I am currently iterating over the resulting list and filtering/sorting out data based on the container id.

As shown below, the Docker CLI _supports_ container selection:

```bash
$ docker container stats --help
Usage:  docker container stats [OPTIONS] [CONTAINER...]

$ docker container stats
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
9b136659b81a   amazing_fermat   0.00%     388KiB / 7.753GiB   0.00%     4.7kB / 0B    0B / 0B     1
94f96d8b61d8   sweet_jennings   0.00%     404KiB / 7.753GiB   0.00%     4.81kB / 0B   0B / 0B     1
118be246cc17   nifty_buck       0.00%     396KiB / 7.753GiB   0.00%     5.07kB / 0B   0B / 0B     1

$ docker container stats 9b136659b81a nifty_buck
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
9b136659b81a   amazing_fermat   0.00%     388KiB / 7.753GiB   0.00%     4.7kB / 0B    0B / 0B     1
118be246cc17   nifty_buck       0.00%     396KiB / 7.753GiB   0.00%     5.07kB / 0B   0B / 0B     1
```

Therefore, I decided to implement this possible as well using _python_on_whales_.

With the proposed alterations you can now do the following:

```python
>>> from python_on_whales import docker
>>> docker.stats(containers=['9b136659b81a', 'nifty_buck'])
[<<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=9b136659b81a, container_id=9b136659b81af7dec9ffbacc58b6e48cf8376cee89e7fabcb0924835237a3c4f, memory_percentage=0.0, memory_used=397312, memory_limit=8324720361, container_name=amazing_fermat, net_upload=5070, net_download=0>,
 <<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=nifty_buck, container_id=118be246cc172ed7b18d43372d1b322d3d1c77c9e44b8d24b155aec0d09f7fd9, memory_percentage=0.0, memory_used=405504, memory_limit=8324720361, container_name=nifty_buck, net_upload=5440, net_download=0>]
```

Whenever the new argument `containers` is ignored, the existing behavior is maintained.

I also implemented some unit tests.

What do you guys think of this?

2023-06-01 23:11 UTC, gabrieldemarmiesse commented
We want to be as close as possible to the CLI so I'm happy with this change. I'll give you a code review in the coming days. Thanks!

2023-06-04 00:05 UTC, gabrieldemarmiesse requested changes

2023-06-04 00:05 UTC, gabrieldemarmiesse commented on python_on_whales/components/container/cli_wrapper.py
> +        containers: Union[ValidContainer, List[ValidContainer]] = [],
Default should be None. [] should return [] as output without executing any command.

2023-06-05 19:42 UTC, MisterOwlPT commented
Hi! 😃 

Thank you for the feedback!
With the new changes the following now happens:

```python
>>> from python_on_whales import docker

>>> # default - shows stats of all containers
>>> docker.stats()
[<<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=9b136659b81a, container_id=9b136659b81af7dec9ffbacc58b6e48cf8376cee89e7fabcb0924835237a3c4f, memory_percentage=0.0, memory_used=397312, memory_limit=8324720361, container_name=amazing_fermat, net_upload=5070, net_download=0>,
 <<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=nifty_buck, container_id=118be246cc172ed7b18d43372d1b322d3d1c77c9e44b8d24b155aec0d09f7fd9, memory_percentage=0.0, memory_used=405504, memory_limit=8324720361, container_name=nifty_buck, net_upload=5440, net_download=0>]

>>> # empty container selection
>>> docker.stats(containers=[])
>>> []

>>> # valid container selection
>>> docker.stats(containers=['nifty_buck'])
[ <<class 'python_on_whales.components.container.cli_wrapper.ContainerStats'> object, attributes are block_read=0, block_write=0, cpu_percentage=0.0, container=nifty_buck, container_id=118be246cc172ed7b18d43372d1b322d3d1c77c9e44b8d24b155aec0d09f7fd9, memory_percentage=0.0, memory_used=405504, memory_limit=8324720361, container_name=nifty_buck, net_upload=5440, net_download=0>]
```

Alterations include additional unit tests.

2023-06-06 06:42 UTC, gabrieldemarmiesse requested changes

2023-06-06 06:42 UTC, gabrieldemarmiesse commented on python_on_whales/components/container/cli_wrapper.py
> +            full_cmd += containers
```suggestion
        if containers == []:
            return []
        elif containers is None:
            # the user didn't provide any filters
            pass
        else:
            full_cmd += to_list(containers)
```
with this the intent is easier to understand

2023-06-06 06:42 UTC, gabrieldemarmiesse commented on python_on_whales/components/container/cli_wrapper.py
>          full_cmd = self.docker_cmd + [
```suggestion
        full_cmd = self.docker_cmd + [
```

2023-06-06 19:47 UTC, gabrieldemarmiesse commented
Thanks a lot! I'm planning to do a release this week :)

2023-06-06 19:47 UTC, gabrieldemarmiesse approved these changes

2023-06-06 19:49 UTC, merged