Update models.py
gabrieldemarmiesse/python-on-whales pull request #477
Opened 2023-09-25 13:56 UTC by jashparekh

2023-09-25 17:44 UTC, gabrieldemarmiesse requested changes
Thanks for the pull request!!! Can we just use more precise types? Thanks!

2023-09-25 17:44 UTC, gabrieldemarmiesse commented on python_on_whales/components/compose/models.py
> +    args: Optional[dict] = None
```suggestion
    dockerfile: Optional[Path] = None
    args: Optional[dict[str, Any]] = None
```

2023-09-27 04:21 UTC, jashparekh commented
> Thanks for the pull request!!! Can we just use more precise types? Thanks!

Made the requested changes, @gabrieldemarmiesse can you take another look?

2023-09-28 15:40 UTC, jashparekh commented
Hey @gabrieldemarmiesse - Following up for your review on this PR

2023-09-28 18:24 UTC, gabrieldemarmiesse commented
Sure, I'll take a look!

2023-09-28 18:25 UTC, gabrieldemarmiesse approved these changes
Very cool :)

2023-09-28 18:25 UTC, merged

2023-09-29 01:29 UTC, jashparekh commented
Thank you @gabrieldemarmiesse, can you also cut a new release with this change?

2023-09-29 08:57 UTC, gabrieldemarmiesse commented
We'll first merge your other PR about pyproject.toml :)