feat: Add `--wait-timeout` option for `docker.compose.up`
gabrieldemarmiesse/python-on-whales pull request #573
Opened 2024-03-23 04:25 UTC by Taragolis

This PR add support for wait timeout, https://docs.docker.com/reference/cli/docker/compose/up/#options

```console
--wait-timeout		Maximum duration to wait for the project to be running|healthy
```

2024-03-23 11:38 UTC, gabrieldemarmiesse commented
I seems that the version of docker compose we use in the CI is not recent enough. Maybe we should update it?

2024-03-23 12:54 UTC, Taragolis commented
Yeah it added in [`v2.17.0`](https://github.com/docker/compose/releases/tag/v2.17.0), let me check locally that compose tests pass in that version

2024-03-23 13:36 UTC, Taragolis commented
I've check it locally with 2.17.0 and 2.17.2 and two tests was failed
```console
================================================================== short test summary info ===================================================================
FAILED tests/python_on_whales/components/test_compose.py::test_project_directory_env_files - python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose --file /home/taragolis/Projects/common/python-on-wh...
FAILED tests/python_on_whales/components/test_compose.py::test_compose_logs_follow - assert 1 >= 5
========================================================== 2 failed, 71 passed in 312.91s (0:05:12) ==========================================================
```

2024-03-23 13:48 UTC, Taragolis commented
I could have a look on this tests and try to adopt tests to the newer version of  docker-compose. Any preference to the target version of docker-compose?

2024-03-23 14:43 UTC, gabrieldemarmiesse commented
The latest one is fine by me

2024-03-24 17:50 UTC, gabrieldemarmiesse commented
@MisterOwlPT  updated the compose version in the CI, let's see if that fixes the tests here

2024-03-29 23:39 UTC, gabrieldemarmiesse requested changes

2024-03-29 23:39 UTC, gabrieldemarmiesse commented on python_on_whales/components/compose/cli_wrapper.py
> +            full_cmd.add_simple_arg("--wait-timeout", wait_timeout)
```suggestion
        full_cmd.add_simple_arg("--wait-timeout", wait_timeout)
```
`àdd_simple_arg` doesn't do anything if the second argument is None

2024-03-29 23:40 UTC, gabrieldemarmiesse approved these changes
Many thanks for the pull request!

2024-04-08 18:25 UTC, gabrieldemarmiesse commented
dang this PR is cursed

2024-04-10 16:48 UTC, merged